(()=>{
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const storeKey='hermes_game_v8_ext'; let saved={sound:true,chests:[],badges:[]};
try{saved={...saved,...JSON.parse(localStorage.getItem(storeKey)||'{}')}}catch(e){}
const save=()=>localStorage.setItem(storeKey,JSON.stringify(saved));
function tone(freq=520,dur=.06,type='triangle'){if(!saved.sound)return;try{window.__v8ac=window.__v8ac||new (AudioContext||webkitAudioContext)();const c=window.__v8ac,o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.value=freq;g.gain.value=.025;o.connect(g);g.connect(c.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,c.currentTime+dur);o.stop(c.currentTime+dur)}catch(e){}}
function sfx(type){if(type==='good'){tone(660,.08);setTimeout(()=>tone(880,.1),70)}else if(type==='loot'){tone(520,.05);setTimeout(()=>tone(760,.06),60);setTimeout(()=>tone(980,.1),120)}else if(type==='bad')tone(180,.11,'sawtooth');else tone(430,.035)}
function burst(x=innerWidth/2,y=innerHeight/2){const l=document.createElement('div');l.className='v8FxLayer';document.body.appendChild(l);for(let i=0;i<20;i++){const p=document.createElement('i');p.textContent=['✨','⭐','💡','⚡'][i%4];const a=Math.random()*Math.PI*2,d=60+Math.random()*110;p.style.left=x+'px';p.style.top=y+'px';p.style.setProperty('--tx',Math.cos(a)*d+'px');p.style.setProperty('--ty',Math.sin(a)*d+'px');p.style.setProperty('--r',(Math.random()*360)+'deg');l.appendChild(p)}setTimeout(()=>l.remove(),900)}
function toast(title,sub=''){const t=document.createElement('div');t.className='v8Toast';t.innerHTML=`<small>DISCOVERY</small><b>${title}</b><span>${sub}</span>`;$('#agentGame')?.appendChild(t);requestAnimationFrame(()=>t.classList.add('show'));setTimeout(()=>t.classList.remove('show'),1800);setTimeout(()=>t.remove(),2200)}
function modal(title,body,icon='💡'){let m=$('#v8Modal');if(!m){m=document.createElement('div');m.id='v8Modal';m.className='v8Modal';m.innerHTML='<div class="v8ModalCard"><button class="v8Close">×</button><div class="v8ModalBody"></div></div>';document.body.appendChild(m);m.querySelector('.v8Close').onclick=()=>m.classList.remove('open');m.onclick=e=>{if(e.target===m)m.classList.remove('open')}}m.querySelector('.v8ModalBody').innerHTML=`<div class="v8ModalIcon">${icon}</div><h2>${title}</h2>${body}`;m.classList.add('open');sfx('good')}
const game=()=>$('#agentGame'), world=()=>$('#gameWorld'), player=()=>$('#player');
function playerPos(){const p=player();return p?{x:parseFloat(p.style.left)||810,y:parseFloat(p.style.top)||650}:{x:810,y:650}}
function addVersion(){const k=$('.gameKicker');if(k&&!k.querySelector('.v8Tag'))k.insertAdjacentHTML('beforeend',' <b class="v8Tag">V8 LIVE</b>');const shell=$('.gameShell');if(shell&&!$('#v8Stamp'))shell.insertAdjacentHTML('beforeend','<div id="v8Stamp" class="v8Stamp">V8 · GAME MODE · 2026.09.12</div>')}
function addHud(){const hud=$('.gameHUD');if(!hud||$('#v8Sound'))return;hud.insertAdjacentHTML('beforeend',`<button class="hudIconBtn" id="v8Sound" title="音效">${saved.sound?'🔊':'🔇'}</button><div class="v8Compass" title="指向目前主線"><span id="v8Arrow">➤</span><b id="v8Distance">任務</b></div><button class="hudIconBtn" id="v8MiniMapBtn" title="小地圖">🧭</button>`);$('#v8Sound').onclick=()=>{saved.sound=!saved.sound;save();$('#v8Sound').textContent=saved.sound?'🔊':'🔇';tone(600,.05)};$('#v8MiniMapBtn').onclick=openMiniMap}
function addAmbient(){const w=world();if(!w||w.querySelector('.v8Ambient'))return;const a=document.createElement('div');a.className='v8Ambient';for(let i=0;i<18;i++){const f=document.createElement('i');f.className='v8Firefly';f.style.left=(5+Math.random()*90)+'%';f.style.top=(8+Math.random()*85)+'%';f.style.animationDelay=(Math.random()*5)+'s';f.style.animationDuration=(4+Math.random()*4)+'s';a.appendChild(f)}w.appendChild(a);$$('.npc').forEach((n,i)=>{n.classList.add('v8NpcAlive');n.style.setProperty('--delay',(i*.23)+'s')})}
const chests=[
{id:'skill',x:720,y:160,label:'Skill 工作卡',icon:'🛠',body:'<p><b>Skill</b> 就像你替 AI 員工寫好的工作 SOP。常做的事情不用每次重講，可以封裝成固定能力。</p><div class="v8Example">例：把「研究新聞 → 選題 → 寫 Reels 腳本」做成一個可重複使用的 Skill。</div>'},
{id:'cron',x:1020,y:840,label:'排程時鐘',icon:'⏰',body:'<p><b>排程</b> 就是「時間到了，Agent 自己開始」。</p><div class="v8Example">例：每天早上 06:00 自動整理 AI 新聞，不需要你先打開電腦提醒它。</div>'},
{id:'workflow',x:245,y:555,label:'工作流碎片',icon:'🧩',body:'<p><b>工作流</b> 是把一件事拆成可交接、可重複、可驗收的步驟。</p><div class="v8Example">人決定目標 → Hermes 思考 → n8n 搬資料 → 工具執行 → 結果回報。</div>'}
];
function addChests(){const w=world();if(!w)return;chests.forEach(c=>{if(w.querySelector(`[data-v8chest="${c.id}"]`))return;const e=document.createElement('button');e.className='v8Chest'+(saved.chests.includes(c.id)?' opened':'');e.dataset.v8chest=c.id;e.style.left=c.x+'px';e.style.top=c.y+'px';e.innerHTML=`<span>🎁</span><small>${saved.chests.includes(c.id)?'已取得':c.label}</small>`;e.onclick=ev=>{ev.stopPropagation();collect(c)};w.appendChild(e)})}
function collect(c){if(!saved.chests.includes(c.id)){saved.chests.push(c.id);save();const el=$(`[data-v8chest="${c.id}"]`);el?.classList.add('opened');if(el)el.querySelector('small').textContent='已取得';burst();sfx('loot');toast('獲得 '+c.label,'不用背，收進你的知識背包')}modal(c.label,c.body,c.icon)}
const sideNPC=[
{id:'api',x:1045,y:585,name:'API 門衛',icon:'🚪',body:'<p>API 不用想得很難。</p><div class="v8BigQuote">「它就是工具之間的正式服務窗口。」</div><p>你照規則把資料交過去，對方就照規則完成動作。新手真正需要先學的是：<b>授權安全、資料格式、成功回執</b>。</p>'},
{id:'vps',x:1505,y:700,name:'雲端旅店老闆',icon:'☁️',body:'<p>VPS 就是一台放在雲端、可以 24 小時開機的電腦。</p><div class="v8BigQuote">「先把流程做成功，再決定要不要讓它 24 小時在線。」</div><p>不需要一開始就花錢租主機。</p>'}
];
function addSideNPC(){const w=world();if(!w)return;sideNPC.forEach((n,i)=>{if(w.querySelector(`[data-v8npc="${n.id}"]`))return;const e=document.createElement('button');e.className='v8SideNpc';e.dataset.v8npc=n.id;e.style.left=n.x+'px';e.style.top=n.y+'px';e.innerHTML=`<span class="v8NpcHead">${n.icon}</span><b>${n.name}</b><small>選修知識</small>`;e.onclick=ev=>{ev.stopPropagation();modal(n.name,n.body,n.icon)};w.appendChild(e)})}
const pipeOrder=['你交代目標','Hermes 思考','搜尋／研究／產出','n8n 接手串接','Notion／Drive／社群執行','Telegram 回報結果'];let pipeStep=0;
function addTerminal(){const w=world();if(!w||$('#v8Terminal'))return;const e=document.createElement('button');e.id='v8Terminal';e.className='v8Terminal';e.style.left='905px';e.style.top='745px';e.innerHTML='<span>⚙️</span><b>工作流組裝台</b><small>第二個小遊戲</small>';e.onclick=ev=>{ev.stopPropagation();openPipeline()};w.appendChild(e)}
function openPipeline(){pipeStep=0;renderPipeline()}
function renderPipeline(){const scrambled=['Notion／Drive／社群執行','Hermes 思考','Telegram 回報結果','你交代目標','n8n 接手串接','搜尋／研究／產出'];const done=pipeOrder.slice(0,pipeStep);const choices=scrambled.filter(x=>!done.includes(x));modal('工作流組裝台',`<p>照事情真正發生的順序點選。這不是背題，而是在理解「誰先做什麼」。</p><div class="v8PipeSlots">${pipeOrder.map((x,i)=>`<span class="${i<pipeStep?'filled':''}">${i<pipeStep?'✅ '+x:(i+1)+'. ？'}</span>`).join('')}</div><div class="v8PipeChoices">${choices.map(x=>`<button data-pipe="${x}">${x}</button>`).join('')}</div><div id="v8PipeFeedback"></div>`,'⚙️');$$('[data-pipe]').forEach(b=>b.onclick=()=>{if(b.dataset.pipe===pipeOrder[pipeStep]){pipeStep++;sfx('good');if(pipeStep===pipeOrder.length){if(!saved.badges.includes('architect'))saved.badges.push('architect');save();burst();modal('🏅 解鎖：流程架構師','<p>你已經自己把整條系統接起來：</p><div class="v8BigQuote">人定目標 → Hermes 思考 → n8n 串接 → 工具執行 → 結果回報</div><p>這就是 Agent 系統最重要的骨架。</p>','🏅');return}renderPipeline()}else{sfx('bad');const f=$('#v8PipeFeedback');if(f){f.textContent='順序不對。提示：先問「誰先決定要做什麼？」';f.className='bad'}}})}
function openMiniMap(){const p=playerPos();modal('AI 自媒體城小地圖',`<div class="v8Map"><i class="you" style="left:${p.x/17.6}%;top:${p.y/10.8}%">你</i><i style="left:43%;top:56%">🧭</i><i style="left:36%;top:25%">⚕</i><i style="left:67%;top:29%">🔗</i><i style="left:22%;top:80%">📸</i><i style="left:78%;top:78%">📊</i><i style="left:84%;top:50%">🚪</i></div><p class="v8MapLegend">跟著 HUD 的紫色箭頭走主線；看到 🎁 可以順手打開知識寶箱。</p>`,'🗺️')}
function questTarget(){const q=($('#questText')?.textContent||'');if(q.includes('小玄'))return[760,620];if(q.includes('顧問'))return[575,355];if(q.includes('Hermes'))return[645,270];if(q.includes('n8n'))return[1175,315];if(q.includes('阿莓'))return[385,865];if(q.includes('重複工作'))return[560,850];if(q.includes('數據'))return[1375,845];if(q.includes('課程之門'))return[1485,555];return null}
let nearExtra=null;
function tick(){const p=playerPos(),q=questTarget();if(q&&$('#v8Arrow')){const dx=q[0]-p.x,dy=q[1]-p.y;$('#v8Arrow').style.transform=`rotate(${Math.atan2(dy,dx)*180/Math.PI}deg)`;$('#v8Distance').textContent=Math.round(Math.hypot(dx,dy)/10)+'m'}let best=null,bd=78;for(const c of chests){if(saved.chests.includes(c.id))continue;const d=Math.hypot(c.x-p.x,c.y-p.y);if(d<bd){best={type:'chest',obj:c};bd=d}}for(const n of sideNPC){const d=Math.hypot(n.x-p.x,n.y-p.y);if(d<bd){best={type:'npc',obj:n};bd=d}}const td=Math.hypot(905-p.x,745-p.y);if(td<bd){best={type:'terminal'};bd=td}nearExtra=best;const h=$('#v8Interact');if(h){h.classList.toggle('show',!!best);h.querySelector('span:last-child').textContent=best?.type==='chest'?'打開寶箱':best?.type==='npc'?'選修對話':best?.type==='terminal'?'玩流程組裝':'互動'}}
function interactExtra(){if(!nearExtra)return false;if(nearExtra.type==='chest')collect(nearExtra.obj);if(nearExtra.type==='npc')modal(nearExtra.obj.name,nearExtra.obj.body,nearExtra.obj.icon);if(nearExtra.type==='terminal')openPipeline();return true}
function addExtraHint(){const shell=$('.gameShell');if(!shell||$('#v8Interact'))return;const h=document.createElement('div');h.id='v8Interact';h.className='v8Interact';h.innerHTML='<b>E</b><span>互動</span>';shell.appendChild(h)}
addEventListener('keydown',e=>{if(e.key.toLowerCase()==='e'&&nearExtra){e.preventDefault();e.stopImmediatePropagation();interactExtra()}},true);
const obs=new MutationObserver(ms=>{for(const m of ms){const el=m.target;if(el.classList?.contains('npc')&&el.classList.contains('completed')&&!el.dataset.v8celebrated){el.dataset.v8celebrated='1';const r=el.getBoundingClientRect();burst(r.left+r.width/2,r.top);toast('任務完成',el.querySelector('.npcBadge')?.textContent||'NPC 對話完成');sfx('good')}if(el.classList?.contains('boss')&&el.classList.contains('defeated')&&!el.dataset.v8boss){el.dataset.v8boss='1';burst();toast('重複工作怪已被修復','工作開始回到正確的人手上')}}});
function init(){if(!game())return setTimeout(init,60);addVersion();addHud();addAmbient();addChests();addSideNPC();addTerminal();addExtraHint();obs.observe(game(),{subtree:true,attributes:true,attributeFilter:['class']});setInterval(tick,140);tick();toast('V8 遊戲版已載入','如果看到這句，就不是舊版');}
init();
})();