(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const tools={
 chatgpt:{name:'ChatGPT',icon:'💬',desc:'回答 / 生成',color:'#75eba6'},
 hermes:{name:'Hermes',icon:'🧠',desc:'判斷 / 研究',color:'#52d9ff'},
 research:{name:'Research',icon:'🔎',desc:'搜尋 / 整理',color:'#68a6ff'},
 writer:{name:'Writer',icon:'✍️',desc:'腳本 / 文案',color:'#ffcb65'},
 n8n:{name:'n8n',icon:'🔗',desc:'串接 / 搬運',color:'#ffb45b'},
 cron:{name:'Cron',icon:'⏰',desc:'定時啟動',color:'#a88bff'},
 human:{name:'Human',icon:'🧑‍💼',desc:'高風險決策',color:'#ff7599'},
 notion:{name:'Notion',icon:'📝',desc:'存檔',color:'#fff'},
 telegram:{name:'Telegram',icon:'📲',desc:'通知',color:'#59bfff'}
};
const levels=[
 {title:'第 1 關｜只會回答，算 Agent 嗎？',desc:'老闆要你「現在寫一篇 IG 文案」。先用最簡單的工具完成。',source:'現在寫一篇 IG 文案',sink:'交付文案',unlocked:['chatgpt'],path:['chatgpt'],note:'一次性的「問 → 答」工作，ChatGPT 就很適合。',queue:[['IG 文案','現在要一篇貼文','一般']],teach:'ChatGPT 很會回答，但這還不是「自己持續工作」。',unlock:['hermes'],reward:120},
 {title:'第 2 關｜每天都做，誰會自己起床？',desc:'需求改了：每天早上都要自己開始準備 AI 新聞。',source:'每天準備 AI 新聞',sink:'每天自動完成',unlocked:['chatgpt','hermes','cron'],path:['cron','hermes'],note:'要「自己開始」需要排程；要「判斷今天做什麼」需要 Agent。',queue:[['每日 AI 新聞','每天 09:00 自動開始','週期']],teach:'Cron 像鬧鐘，Hermes 像被鬧鐘叫醒後真的開始工作的員工。',unlock:['cron'],reward:160},
 {title:'第 3 關｜大腦不該自己搬貨',desc:'Hermes 研究完主題後，要把結果存進 Notion，完成時通知 Telegram。',source:'研究 → 存檔 → 通知',sink:'Notion + Telegram',unlocked:['hermes','research','n8n','notion','telegram'],path:['hermes','research','n8n','notion','telegram'],note:'需要判斷的交給 Hermes；固定串接、搬資料交給 n8n。',queue:[['研究 AI 新聞','挑最值得做的一題','判斷'],['存進 Notion','固定資料搬運','執行'],['Telegram 通知','完成後提醒你','執行']],teach:'Hermes 是大腦，n8n 是輸送帶。兩個合作，才是真正可長期運作的系統。',unlock:['n8n','notion','telegram'],reward:220},
 {title:'第 4 關｜內容工廠開始量產',desc:'今天要做 IG。先研究，再產生適合 IG 的腳本，最後存進 Notion。',source:'IG 今日內容',sink:'IG 草稿完成',unlocked:['hermes','research','writer','n8n','notion'],path:['hermes','research','writer','n8n','notion'],note:'研究、寫作、執行是不同工序；拆開後才容易維護與放大。',queue:[['找題目','比較熱門程度','研究'],['寫 Reels','Hook + 腳本','創作'],['存草稿','進入 Notion','執行']],teach:'真正的 AI 系統不是一個 Prompt，而是一條可以反覆跑的生產線。',unlock:['writer'],reward:260},
 {title:'第 5 關｜有些事情不能全自動',desc:'突然出現一則高爭議品牌事件。你可以研究與整理，但發布前必須有人確認。',source:'高風險事件',sink:'安全發布',unlocked:['hermes','research','writer','human','n8n'],path:['hermes','research','writer','human','n8n'],note:'政治、法律、危機、公關等高風險內容，要加入 Human Approval。',queue:[['危機事件','需要快速了解狀況','高風險'],['對外內容','不能直接自動發布','人工確認']],teach:'好的 Agent 系統不是「全自動」，而是知道什麼時候必須把決策交回人類。',unlock:['human'],reward:320},
 {title:'Boss｜星期一早上 9 點',desc:'AI 公司同時收到研究、內容、排程、存檔與通知。請組出一條完整、穩定的工作線。',source:'星期一 09:00 任務潮',sink:'全部準時完成',unlocked:['cron','hermes','research','writer','human','n8n','notion','telegram'],path:['cron','hermes','research','writer','n8n'],altPaths:[['cron','hermes','research','writer','human']],note:'最後一關不是背答案，而是看懂：啟動 → 思考 → 研究 → 產出 → 執行／審核。',queue:[['AI 新聞','今天最重要的 5 則','研究'],['IG Reels','今日短影音腳本','創作'],['Notion','歸檔素材','執行'],['Telegram','回報完成','執行']],teach:'你剛剛玩的「工廠」，其實就是 Agent 工作流的核心：把角色分工與資料流設計好。',unlock:['🏆 AI Workflow Builder'],reward:500}
];
let state={level:0,slots:[null,null,null,null,null],stars:0,coins:320,streak:0,completed:[],sound:true,tutorialDone:false};
try{state={...state,...JSON.parse(localStorage.getItem('agent_factory_v1')||'{}')}}catch(e){}
const save=()=>{try{localStorage.setItem('agent_factory_v1',JSON.stringify(state))}catch(e){}};
const sound=(freq=420,dur=.06)=>{if(!state.sound||!window.AudioContext)return;try{const ac=sound.ac||(sound.ac=new AudioContext());const o=ac.createOscillator(),g=ac.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.05,ac.currentTime);g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+dur);o.connect(g);g.connect(ac.destination);o.start();o.stop(ac.currentTime+dur)}catch(e){}};
function render(){const L=levels[state.level];$('#levelNum').textContent=state.level+1;$('#stars').textContent=state.stars;$('#coins').textContent=state.coins;$('#streak').textContent=state.streak;$('#missionTitle').textContent=L.title;$('#missionDesc').textContent=L.desc;$('#sourceLabel').textContent=L.source;$('#sinkLabel').textContent=L.sink;$('#lessonNote span').textContent=L.note;renderLevels();renderPalette();renderSlots();renderQueue();renderPedia();updateEfficiency();save()}
function renderLevels(){const map=$('#levelMap');map.innerHTML=levels.map((l,i)=>`<button class="level-btn ${i===state.level?'active':''} ${state.completed.includes(i)?'done':''} ${i>Math.max(0,(state.completed.length?Math.max(...state.completed)+1:0))?'lock':''}" data-lv="${i}"><b>${i<5?'LEVEL '+(i+1):'BOSS'}</b><small>${l.title.replace(/^.*｜/,'')}</small></button>`).join('');$$('.level-btn').forEach(b=>b.addEventListener('click',()=>{const i=+b.dataset.lv;if(b.classList.contains('lock'))return;state.level=i;state.slots=[null,null,null,null,null];$('#resultCard').className='result-card';render()}))}
function renderPalette(){const L=levels[state.level],p=$('#palette');p.innerHTML='<span class="palette-label">工作站</span>'+Object.entries(tools).map(([id,t])=>`<button class="tool ${id} ${L.unlocked.includes(id)?'':'lock'}" data-tool="${id}" type="button"><span class="ico">${t.icon}</span><b>${t.name}</b><small>${t.desc}</small></button>`).join('');$$('.tool:not(.lock)').forEach(b=>b.addEventListener('click',()=>addTool(b.dataset.tool)))}
function addTool(id){const idx=state.slots.findIndex(x=>!x);if(idx<0){flashMessage('管線滿了，先移除一個工作站。',false);return}state.slots[idx]=id;sound(520);renderSlots();save()}
function renderSlots(){$$('.slot').forEach((el,i)=>{const id=state.slots[i];el.className='slot'+(id?'':' empty');if(id){const t=tools[id];el.innerHTML=`<div class="big">${t.icon}</div><b>${t.name}</b><span>${t.desc}</span>`;el.onclick=()=>{state.slots[i]=null;renderSlots();save()}}else{el.innerHTML='';el.onclick=null}})}
function renderQueue(){const q=$('#queue');q.innerHTML=levels[state.level].queue.map(x=>`<div class="ticket"><div class="ticket-top"><b>${x[0]}</b><span>${x[2]}</span></div><p>${x[1]}</p></div>`).join('')}
function renderPedia(){const known=new Set(['chatgpt']);levels.forEach((l,i)=>{if(state.completed.includes(i))l.unlocked.forEach(x=>known.add(x))});levels[state.level].unlocked.forEach(x=>known.add(x));const ids=['chatgpt','hermes','cron','research','writer','n8n','human','notion','telegram'];$('#pedia').innerHTML=ids.map(id=>{const t=tools[id];return `<div class="pedia ${known.has(id)?'':'lock'}"><span>${t.icon}</span><b>${t.name}</b><small>${t.desc}</small></div>`}).join('')}
function updateEfficiency(){const pct=Math.min(100,25+state.completed.length*12+state.streak*3);$('#efficiencyText').textContent=pct+'%';$('#efficiencyBar').style.width=pct+'%'}
function clearSlots(){state.slots=[null,null,null,null,null];$$('.slot').forEach(x=>x.classList.remove('running','error','ok'));$('#taskToken').className='task-token';$('#bottleneck').className='bottleneck';$('#resultCard').className='result-card';renderSlots();save()}
function currentPath(){return state.slots.filter(Boolean)}
function pathOk(){const p=currentPath(),L=levels[state.level];const eq=a=>a.length===p.length&&a.every((x,i)=>x===p[i]);return eq(L.path)||(L.altPaths||[]).some(eq)}
async function run(){const p=currentPath(),L=levels[state.level];if(!p.length){flashMessage('先把工作站放進管線。',false);return}$('#runBtn').disabled=true;$$('.slot').forEach(x=>x.classList.remove('error','ok'));const token=$('#taskToken');token.className='task-token show';const positions=getSlotPositions();const src=getCenter($('#sourceTerminal')),sink=getCenter($('#sinkTerminal'));moveToken(src);await wait(350);let mismatch=-1;for(let i=0;i<p.length;i++){const el=$$(`.slot`)[i];el.classList.add('running');moveToken(positions[i]);sound(360+i*50,.08);await wait(650);el.classList.remove('running');const expected=L.path[i];if(expected&&p[i]!==expected&&mismatch<0)mismatch=i}
moveToken(sink);await wait(650);const ok=pathOk();token.classList.add(ok?'success':'fail');if(ok){$$('.slot').slice(0,p.length).forEach(x=>x.classList.add('ok'));flashMessage('流程跑通了！任務已經自己走完整條線。',true);spawnSparks(sink.x,sink.y);state.streak++;state.stars+=3;state.coins+=L.reward;if(!state.completed.includes(state.level))state.completed.push(state.level);save();setTimeout(()=>showComplete(),700)}else{state.streak=0;if(mismatch>=0)$$('.slot')[mismatch].classList.add('error');const hint=getHint(p,L);flashMessage(hint,false);const r=$('#resultCard');r.className='result-card show bad';r.querySelector('b').textContent='⚠️ 工廠塞車了';r.querySelector('p').textContent=hint}
$('#runBtn').disabled=false;save();renderTopOnly()}
function renderTopOnly(){$('#stars').textContent=state.stars;$('#coins').textContent=state.coins;$('#streak').textContent=state.streak;updateEfficiency()}
function getHint(p,L){if(state.level===0)return '這題只是「現在幫我寫一次」，先用 ChatGPT 就夠了。';if(state.level===1){if(!p.includes('cron'))return '每天固定時間自己開始，需要一個「鬧鐘」：Cron。';return '被叫醒之後還要判斷今天做什麼，這部分交給 Hermes。'}if(state.level===2){if(!p.includes('n8n'))return '研究完之後要存檔、通知，這些固定搬運工作交給 n8n。';return '順序想成：大腦先判斷 → 搜尋研究 → n8n 接手 → 工具執行。'}if(state.level===3)return '內容工廠順序：Hermes 決定 → Research 找資料 → Writer 寫 → n8n 搬運 → Notion 存檔。';if(state.level===4){if(!p.includes('human'))return '這是高風險事件，少了 Human Approval。先讓 AI 準備，但最後由人決定。';return '人工審核要放在「內容產生後、真正執行前」。'}return 'Boss 的核心順序是：Cron 啟動 → Hermes 判斷 → Research 研究 → Writer 產出 → n8n 執行。'}
function flashMessage(text,good){const b=$('#bottleneck');b.textContent=text;b.className='bottleneck show '+(good?'good':'bad');setTimeout(()=>b.classList.remove('show'),3600)}
function getCenter(el){const f=$('#factory').getBoundingClientRect(),r=el.getBoundingClientRect();return{x:r.left-f.left+r.width/2-16,y:r.top-f.top+r.height/2-16}}
function getSlotPositions(){return $$('.slot').map(getCenter)}function moveToken(p){const t=$('#taskToken');t.style.left=p.x+'px';t.style.top=p.y+'px'}function wait(ms){return new Promise(r=>setTimeout(r,ms))}
function spawnSparks(x,y){const fx=$('#factoryFx');for(let i=0;i<20;i++){const s=document.createElement('i');s.className='spark';s.style.left=x+'px';s.style.top=y+'px';s.style.setProperty('--dx',(Math.random()*140-70)+'px');s.style.setProperty('--dy',(Math.random()*120-60)+'px');fx.appendChild(s);setTimeout(()=>s.remove(),800)}}
function showComplete(){const L=levels[state.level];$('#modalStars').textContent='⭐⭐⭐';$('#modalTitle').textContent=state.level===levels.length-1?'你真的把 AI 公司跑起來了！':'任務完成！';$('#modalText').textContent=L.teach;$('#unlocks').innerHTML=(L.unlock||[]).map(x=>`<span>🔓 ${tools[x]?.name||x}</span>`).join('');$('#nextLevel').textContent=state.level===levels.length-1?'回到第一關':'下一關 →';$('#completeModal').classList.add('show')}
function nextLevel(){ $('#completeModal').classList.remove('show'); state.level=state.level===levels.length-1?0:state.level+1;state.slots=[null,null,null,null,null];render();window.scrollTo({top:0,behavior:'smooth'})}
function start(demo=false){$('#splash').style.display='none';$('#game').classList.add('active');render();if(demo){state.level=2;state.slots=['hermes','research','n8n','notion','telegram'];render();setTimeout(run,700)}else if(!state.tutorialDone&&innerWidth>760)setTimeout(startTutorial,400)}
function startTutorial(){const steps=[['#palette','① 選工作站','下面是你的工具箱。點一下工作站，就會加入管線。'],['#pipeline','② 組工作流','資料會從左邊進來，依序經過你放進去的工作站。'],['#runBtn','③ 按 RUN 看結果','流程正確就會自己跑完；做錯會直接告訴你塞在哪裡。']];let i=0;const tut=$('#tutorial'),spot=$('#spotlight'),coach=$('#coach');tut.classList.add('show');function draw(){const [sel,title,text]=steps[i],el=$(sel),r=el.getBoundingClientRect();spot.style.left=(r.left-6)+'px';spot.style.top=(r.top-6)+'px';spot.style.width=(r.width+12)+'px';spot.style.height=(r.height+12)+'px';coach.querySelector('b').textContent=title;coach.querySelector('p').textContent=text;coach.style.left=Math.min(innerWidth-372,Math.max(12,r.left))+'px';coach.style.top=(r.bottom+12<innerHeight-150?r.bottom+12:Math.max(12,r.top-150))+'px'}draw();$('#coachNext').onclick=()=>{i++;if(i>=steps.length){tut.classList.remove('show');state.tutorialDone=true;save()}else draw()}}
$('#startGame').addEventListener('click',()=>start(false));$('#quickDemo').addEventListener('click',()=>start(true));$('#runBtn').addEventListener('click',run);$('#clearBtn').addEventListener('click',clearSlots);$('#nextLevel').addEventListener('click',nextLevel);$('#replayLevel').addEventListener('click',()=>{$('#completeModal').classList.remove('show');clearSlots()});$('#soundBtn').addEventListener('click',e=>{state.sound=!state.sound;e.currentTarget.textContent=state.sound?'🔊':'🔇';save()});addEventListener('resize',()=>{if($('#taskToken').classList.contains('show'))moveToken(getCenter($('#sourceTerminal')))});
render();
})();