(()=>{'use strict';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const audio={ctx:null,music:null,on:true,ensure(){const A=window.AudioContext||window.webkitAudioContext;if(!A)return null;this.ctx=this.ctx||new A();if(this.ctx.state==='suspended')this.ctx.resume();return this.ctx},tone(f=440,d=.06,type='sine',g=.035,delay=0){if(!this.on)return;const c=this.ensure();if(!c)return;try{const o=c.createOscillator(),v=c.createGain(),t=c.currentTime+delay;o.type=type;o.frequency.value=f;v.gain.setValueAtTime(g,t);v.gain.exponentialRampToValueAtTime(.001,t+d);o.connect(v);v.connect(c.destination);o.start(t);o.stop(t+d+.02)}catch(e){}},click(){this.tone(520,.04,'square',.022)},add(){this.tone(420,.05,'triangle',.035);this.tone(660,.06,'triangle',.025,.04)},run(){[320,410,520].forEach((f,i)=>this.tone(f,.08,'square',.025,i*.05))},success(){[523,659,784,1047].forEach((f,i)=>this.tone(f,.16,'triangle',.045,i*.09))},fail(){this.tone(180,.18,'sawtooth',.035);this.tone(135,.2,'square',.025,.08)},boost(){[420,620,900].forEach((f,i)=>this.tone(f,.12,'square',.03,i*.06))},startMusic(){if(this.music)return;const notes=[196,247,294,330,294,247,220,262];let i=0;this.music=setInterval(()=>this.tone(notes[i++%notes.length],.16,'sine',.011),360)},stopMusic(){clearInterval(this.music);this.music=null}};
function vib(p){if(navigator.vibrate)navigator.vibrate(p)}
const factory=$('#factory');if(factory){const workers=document.createElement('div');workers.className='v2-workers';workers.innerHTML='<i class="v2-bot b1"></i><i class="v2-bot b2"></i><i class="v2-bot b3"></i>';factory.appendChild(workers);const weather=document.createElement('div');weather.className='v2-weather';weather.id='v2Weather';weather.textContent='🌈 WARM-UP';factory.appendChild(weather);const combo=document.createElement('div');combo.className='v2-combo';combo.id='v2Combo';combo.textContent='PERFECT!';factory.appendChild(combo);const fx=document.createElement('div');fx.className='v2-fx';fx.id='v2Fx';factory.appendChild(fx)}
const toast=document.createElement('div');toast.className='v2-toast';toast.id='v2Toast';document.body.appendChild(toast);
function showToast(text,good=true,d=3200){toast.textContent=text;toast.className='v2-toast show '+(good?'good':'bad');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),d)}
const events=['🌈 WARM-UP','⏰ MORNING SHIFT','📦 LOGISTICS RUSH','🔥 CONTENT FEVER','🚨 RISK ALERT','👾 MONDAY BOSS'];function updateEvent(){const m=($('#missionTitle')?.textContent||'');let idx=0;if(m.includes('第 2'))idx=1;else if(m.includes('第 3'))idx=2;else if(m.includes('第 4'))idx=3;else if(m.includes('第 5'))idx=4;else if(m.includes('Boss'))idx=5;const e=$('#v2Weather');if(e)e.textContent=events[idx]}
new MutationObserver(updateEvent).observe($('#missionTitle'),{childList:true,subtree:true});updateEvent();
const topStats=$('.top-stats');if(topStats){const music=document.createElement('button');music.className='v2-top-btn';music.id='v2Music';music.title='背景音樂';music.textContent='🎵';topStats.prepend(music);music.addEventListener('click',()=>{audio.ensure();if(audio.music){audio.stopMusic();music.textContent='🎵';showToast('背景音樂已關閉',true)}else{audio.startMusic();music.textContent='🎶';showToast('背景音樂已開啟',true)}})}
const runArea=$('.run-area');if(runArea){const hint=document.createElement('button');hint.className='v2-hint';hint.id='v2Hint';hint.textContent='💡 給我提示';const boost=document.createElement('button');boost.className='v2-boost';boost.id='v2Boost';boost.textContent='✨ PARTY BOOST';runArea.insertBefore(hint,$('#clearBtn'));runArea.insertBefore(boost,$('#clearBtn'));const help=document.createElement('div');help.className='v2-help';help.textContent='電腦：1～9 加工作站 · R 執行 · C 清空 · H 提示 · M 靜音';runArea.appendChild(help)}
const dock=document.createElement('div');dock.className='v2-mobile-dock';dock.innerHTML='<button class="v2-m-clear" type="button">清空</button><button class="v2-m-hint" type="button">💡 提示</button><button class="v2-m-run" type="button">▶ RUN</button>';document.body.appendChild(dock);
function hintText(){const m=$('#missionTitle')?.textContent||'';if(m.includes('第 1'))return '這題只要「現在回答一次」，ChatGPT 就夠了。';if(m.includes('第 2'))return '先用 Cron 當鬧鐘，再讓 Hermes 起床做判斷。';if(m.includes('第 3'))return 'Hermes → Research → n8n → Notion → Telegram。';if(m.includes('第 4'))return 'Hermes → Research → Writer → n8n → Notion。';if(m.includes('第 5'))return '高風險內容：Hermes → Research → Writer → Human → n8n。';return 'Boss：Cron → Hermes → Research → Writer → n8n（或 Human）。'}
$('#v2Hint')?.addEventListener('click',()=>{audio.tone(740,.1,'triangle',.035);showToast('💡 '+hintText(),true,5200)});dock.querySelector('.v2-m-hint').addEventListener('click',()=>$('#v2Hint')?.click());dock.querySelector('.v2-m-clear').addEventListener('click',()=>$('#clearBtn')?.click());dock.querySelector('.v2-m-run').addEventListener('click',()=>$('#runBtn')?.click());
let boosting=false;$('#v2Boost')?.addEventListener('click',()=>{boosting=!boosting;factory?.classList.toggle('v2-boosting',boosting);$('#v2Boost').textContent=boosting?'✨ PARTY MODE ON':'✨ PARTY BOOST';audio.boost();vib(25);showToast(boosting?'PARTY MODE！輸送帶與場景特效全開 ✨':'PARTY MODE 關閉',true)});
function burst(){const fx=$('#v2Fx'),sink=$('#sinkTerminal');if(!fx||!sink)return;const fr=factory.getBoundingClientRect(),r=sink.getBoundingClientRect(),x=r.left-fr.left+r.width/2,y=r.top-fr.top+r.height/2;const colors=['#2be9ff','#ff4fa3','#ffd74f','#87f34d','#a46cff'];for(let i=0;i<34;i++){const s=document.createElement('i');s.className='v2-spark';s.style.left=x+'px';s.style.top=y+'px';s.style.background=colors[i%colors.length];s.style.setProperty('--dx',(Math.random()*230-115)+'px');s.style.setProperty('--dy',(Math.random()*190-95)+'px');fx.appendChild(s);setTimeout(()=>s.remove(),900)}}
let lastStars=Number($('#stars')?.textContent||0);new MutationObserver(()=>{const now=Number($('#stars')?.textContent||0);if(now>lastStars){lastStars=now;burst();audio.success();vib([20,30,20]);const c=$('#v2Combo');if(c){const streak=$('#streak')?.textContent||'1';c.textContent=Number(streak)>1?'COMBO x'+streak+'!':'PERFECT!';c.classList.remove('show');void c.offsetWidth;c.classList.add('show')}showToast('✅ 任務完成！工廠運轉成功',true)}else lastStars=now}).observe($('#stars'),{childList:true,subtree:true});
const result=$('#resultCard');if(result)new MutationObserver(()=>{if(result.classList.contains('bad')){audio.fail();vib([70,30,70]);showToast('⚠️ 流程塞車了：看看哪個工作站亮紅燈',false)}}).observe(result,{attributes:true,attributeFilter:['class']});
$('#runBtn')?.addEventListener('click',()=>{audio.ensure();audio.run()});$('#clearBtn')?.addEventListener('click',()=>audio.click());$('#soundBtn')?.addEventListener('click',()=>{audio.on=$('#soundBtn').textContent!=='🔇'});
document.addEventListener('click',e=>{const t=e.target.closest('.tool:not(.lock)');if(t){audio.ensure();audio.add();vib(12)}const lv=e.target.closest('.level-btn:not(.lock)');if(lv)audio.click()});
addEventListener('keydown',e=>{if(!$('#game')?.classList.contains('active')||['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;const k=e.key.toLowerCase();if(k==='r'){e.preventDefault();$('#runBtn')?.click()}else if(k==='c')$('#clearBtn')?.click();else if(k==='h')$('#v2Hint')?.click();else if(k==='m')$('#soundBtn')?.click();else if(/^[1-9]$/.test(k)){const tools=$$('.tool:not(.lock)');const i=Number(k)-1;if(tools[i])tools[i].click()}});
const startGame=$('#startGame'),quick=$('#quickDemo');function introFeedback(){audio.ensure();showToast(innerWidth<=760?'📱 點工作站加入管線，底部 RUN 執行。':'⌨️ 1～9 加工作站，R RUN，H 提示。',true,4300)}startGame?.addEventListener('click',()=>setTimeout(introFeedback,220));quick?.addEventListener('click',()=>setTimeout(introFeedback,220));
})();