(()=>{
const hermesArt='https://web-assets.nousresearch.com/nousnet-web/img/desktop/badge.23c0ee96805e7e31.webp';
const icons={n8n:'https://n8n.io/brandguidelines/logo-dark.svg',telegram:'https://cdn.simpleicons.org/telegram/26A5E4',notion:'https://cdn.simpleicons.org/notion/000000',gmail:'https://cdn.simpleicons.org/gmail/EA4335',drive:'https://cdn.simpleicons.org/googledrive/4285F4'};
const outcomes=[['📰','每日 AI 新聞 Agent','每天自動整理值得關注的 AI 新聞，再交給你決定怎麼用。'],['🎯','自動選題 Agent','從大量資訊中挑出最值得做的一題，不再每天想題目。'],['📸','IG 文案 Agent','把核心觀點轉成 Hook、Caption、輪播大綱與 Reels 腳本。'],['▶️','YouTube 腳本 Agent','研究資料後整理標題、開場、段落與 CTA。'],['🕵️','競品監控 Agent','固定追蹤競品、內容與市場變化，整理成簡報。'],['🧠','個人知識庫 Agent','把資料、檔案、筆記整理成能持續使用的工作記憶。'],['🔎','自動研究 Agent','針對一個題目搜尋、比較、整理來源與重點。'],['📲','Telegram AI 助理','人在手機上也能下任務、查狀態、收到完成通知。'],['🔗','n8n 自動化工作流','把 AI 的決策送進 Notion、Drive、Gmail、資料庫等工具。'],['🚀','自己的 AI 自媒體系統','把研究、創作、整理、排程與回報組成自己的工作系統。']];
const faqs=[
['完全不會寫程式可以嗎？','可以。這堂課的核心不是教你成為工程師，而是教你把工作拆成 AI 看得懂、工具接得起來的流程。會用電腦、會照步驟操作，就能從最小版本開始。'],
['Hermes 跟 ChatGPT 到底差在哪？','可以把 ChatGPT 想成很聰明的顧問：你問，它回答。Hermes 更像一位可長期工作的 AI 員工：除了對話，也能使用工具、處理檔案、記住工作方式、建立 Skills、執行排程，並透過 Telegram／Discord 等入口接收任務。'],
['為什麼不用 ChatGPT 就好？','如果你的工作只是偶爾問問題、寫一篇文案，ChatGPT 已經很好用。當你希望「每天固定做、會用工具、會接續上次的工作、會自己執行流程」時，Agent 型系統才開始有價值。'],
['一定要 n8n 嗎？','不一定。n8n 是很適合教學與實作的自動化管線，但真正重要的是「Hermes 負責判斷，外部工作流負責穩定串工具」這個概念。未來也可以換成其他自動化平台。'],
['一定要買 VPS 嗎？','不用一開始就買。你可以先在自己的電腦把第一條流程跑通。只有當你真的需要 24 小時無人值守時，才值得把它搬到雲端或 VPS。'],
['需要 API Key 嗎？','有些工具會需要、有些不一定。課程會先用最少必要的方式完成成果，再逐步加入正式授權。重點是理解「憑證要安全保存」，不是背一堆 API 名稱。'],
['會不會很難？','真正困難的通常不是寫程式，而是不知道整套系統各自負責什麼。網站與課程會先讓你看懂角色分工，再一步一步做出第一個成果。'],
['每個月需要多少成本？','沒有固定答案。可以先用本機與免費層做測試；當你需要更好的模型、更多工具使用量或 24/7 雲端執行時才增加成本。課程的原則是先做出能用的 MVP，再決定哪些費用值得付。'],
['學完到底能做什麼？','不是只會「裝 Hermes」或「拉 n8n 節點」。目標是你能自己設計一個 AI 工作流程：給任務、研究、產出內容、串接工具、回報結果，並逐步變成自己的自媒體工作系統。'],
['手機可以控制嗎？','可以。Hermes 官方支援多種訊息入口，包含 Telegram、Discord 等。你可以把手機當成遙控器：下任務、查結果、收到通知，高風險工作也可以要求先由你確認。']
];
const demoData={
 ig:{label:'我要經營 IG',prompt:'幫我製作今天的 IG AI 新聞內容。',steps:['Hermes 收到任務','搜尋今日 AI 新聞','比較熱門程度','挑選最值得做的題目','研究可信資料','產生 Reels 腳本','產生 IG Caption','交給 n8n','存入 Notion','Telegram 通知完成']},
 yt:{label:'我要做 YouTube',prompt:'幫我準備今天的 YouTube AI 主題。',steps:['Hermes 收到任務','搜尋熱門問題','比較搜尋與討論熱度','挑選主題角度','研究資料與案例','產生影片大綱','寫開場與完整腳本','交給 n8n','存入 Google Drive','Telegram 通知完成']},
 blog:{label:'我要寫部落格',prompt:'幫我準備一篇今天值得發布的 AI 文章。',steps:['Hermes 收到任務','搜尋產業變化','挑選適合讀者的題目','蒐集資料','整理文章架構','產生初稿','自我檢查與修正','交給 n8n','建立 Notion 草稿','Telegram 通知完成']},
 news:{label:'我要每天追蹤 AI 新聞',prompt:'每天整理最值得我知道的 5 則 AI 新聞。',steps:['排程時間到','Hermes 自動啟動','搜尋多個新聞來源','去除重複消息','判斷重要程度','整理重點與來源','建立每日摘要','交給 n8n','存入知識庫','Telegram 推播完成']}
};
function outcomesHtml(){return outcomes.map((x,i)=>`<article class="outcomeCard reveal"><div class="outcomeIcon">${x[0]}</div><h3>${i+1}. ${x[1]}</h3><p>${x[2]}</p><div class="outcomeMini"></div></article>`).join('')}
function faqHtml(){return faqs.map((x,i)=>`<div class="faqItem reveal"><button class="faqQ" type="button"><span>${x[0]}</span><i>＋</i></button><div class="faqA">${x[1]}</div></div>`).join('')}
const overview=document.getElementById('overview'); if(!overview)return;
overview.innerHTML=`
<nav class="salesNav"><div class="salesBrand"><span class="salesMark">H</span><span>Hermes 自媒體學院</span></div><a href="#what-hermes">Hermes 是什麼</a><a href="#demo">3 分鐘體驗</a><a href="#outcomes">課程成果</a><a href="#faq">FAQ</a><button class="salesTopCta" data-scroll="#demo">讓 AI 替我工作</button></nav>
<div class="readingProgress" id="readingProgress"></div>
<section class="salesHero">
 <div><span class="salesEyebrow">AI AGENT × 自媒體自動化｜課前體驗</span><h1>打造一支 <em>24 小時工作的 AI 自媒體團隊</em></h1><p class="salesLead">從找題目、研究、寫稿、整理素材到排程與通知，讓 AI Agent 協助完成原本需要你反覆處理的工作。你不需要先學寫程式，先看懂「AI 員工怎麼工作」。</p><div class="salesHeroActions"><button class="salesPrimary" data-scroll="#demo">開始 3 分鐘 AI Agent 體驗</button><button class="salesSecondary" data-scroll="#what-hermes">先看 Hermes 到底是什麼</button></div><div class="trustRow"><span class="trustPill"><i>✓</i>外行人也能理解</span><span class="trustPill"><i>✓</i>先做結果再學技術</span><span class="trustPill"><i>✓</i>手機也能操作</span></div></div>
 <div class="heroDemo"><div class="heroGlass"><div class="fakeWindow"><div class="fakeBar"><i></i><i></i><i></i></div><div class="heroAgent"><div class="hermesPortrait"><img src="${hermesArt}" alt="Hermes 官方視覺"></div><div class="heroAgentText"><strong>Hermes Agent 開始工作</strong><span>你只需要先說清楚想完成什麼</span></div></div><div class="commandBubble">「幫我準備今天的 AI 自媒體內容。」</div><div class="animatedPipeline"><div class="pipeStep"><span class="pipeIcon">💬</span><b>收到任務</b> 理解你的目標</div><div class="pipeStep"><span class="pipeIcon">🧠</span><b>Hermes 思考</b> 決定要做什麼</div><div class="pipeStep"><span class="pipeIcon">🔎</span><b>搜尋研究</b> 找資料與題目</div><div class="pipeStep"><span class="pipeIcon">✍️</span><b>產生內容</b> 腳本、文案、素材指令</div><div class="pipeStep"><span class="pipeIcon">🔗</span><b>交給 n8n</b> 串接後續工具</div><div class="pipeStep"><span class="pipeIcon">📂</span><b>Notion / Drive / 社群</b> 自動送到指定位置</div><div class="pipeStep"><span class="pipeIcon">✅</span><b>完成</b> Telegram 通知你結果</div></div></div></div>
</section>
<section class="salesSection"><div class="sectionHead sectionCenter reveal"><span class="sectionKicker">你真正缺的不是更多 AI 工具</span><h2>你缺的是一套「工作會自己往下走」的系統</h2><p>很多人已經會用 ChatGPT，但每天還是在重複找資料、複製貼上、整理檔案、切換網站。AI 很聰明，工作卻沒有真的變少。</p></div><div class="salesGrid3"><div class="salesCard painCard reveal"><div class="salesCardIcon">🌀</div><h3>每天重新開始</h3><p>昨天研究過的流程，今天又要重新說一次。AI 沒有真正進入你的工作系統。</p></div><div class="salesCard painCard reveal"><div class="salesCardIcon">🧩</div><h3>工具很多，彼此不會合作</h3><p>ChatGPT、Notion、Drive、Telegram 都很好用，但中間還是你本人搬資料。</p></div><div class="salesCard painCard reveal"><div class="salesCardIcon">⏳</div><h3>時間都花在重複動作</h3><p>找題目、查資料、改格式、存檔、通知，本來就是最適合交給系統的工作。</p></div></div></section>
<section class="salesSection"><div class="sectionHead reveal"><span class="sectionKicker">BEFORE / AFTER</span><h2>同樣是經營自媒體，工作方式可以完全不同</h2><p>不是追求「完全不做事」，而是把重複、可規則化的工作交出去，把人的時間留給判斷、創意與最後決策。</p></div><div class="baWrap"><div class="baPanel reveal"><span class="baTag">以前：你自己當整間公司</span><h3>每一站都要親自做</h3><div class="manualFlow"><div class="manualStep">🔎 人工找新聞</div><div class="manualStep">💡 想主題</div><div class="manualStep">📚 查資料</div><div class="manualStep">✍️ 寫腳本</div><div class="manualStep">📝 修改與整理素材</div><div class="manualStep">📤 上傳與排程</div></div></div><div class="baPanel after reveal"><span class="baTag">之後：你有一位 AI 員工</span><h3>你交代目標，系統開始跑</h3><div class="afterPrompt">「幫我準備今天的 AI 自媒體內容。」</div><div class="agentRunMini"><span>研究</span><span>選題</span><span>寫稿</span><span>整理</span><span>存檔</span><span>串接</span><span>通知</span><span>回報</span></div></div></div></section>
<section class="salesSection" id="what-hermes"><div class="sectionHead reveal"><span class="sectionKicker">HERMES 到底是什麼？</span><h2>ChatGPT 像聰明顧問，Hermes 更像可以持續工作的 AI 員工</h2><p>先不用管 Agent、Skill、Gateway 這些名詞。你只要先記住一件事：Hermes 不只跟你聊天，它的設計目標是「接到任務後，能繼續使用工具把事情往下做」。</p></div><div class="compareWrap"><article class="compareCard reveal"><div class="compareIcon">💬</div><h3>ChatGPT</h3><div class="sub">像一位很聰明的顧問</div><div class="featureList"><span>回答問題</span><span>幫你想點子</span><span>寫文章</span><span>分析資料</span></div></article><article class="compareCard featured reveal"><div class="compareIcon"><img src="${hermesArt}" alt="Hermes"></div><h3>Hermes Agent</h3><div class="sub">像一位能長期工作的 AI 員工</div><div class="featureList"><span>🧠 思考與規劃</span><span>🛠 使用工具</span><span>📁 處理檔案</span><span>🧩 建立 Skills</span><span>🗂 記住工作方式</span><span>⏰ 執行排程</span><span>📲 接 Telegram / Discord</span><span>🔎 搜尋與研究</span></div></article></div></section>
<section class="salesSection" id="hermes-n8n"><div class="sectionHead sectionCenter reveal"><span class="sectionKicker">最重要的分工</span><h2>Hermes 是大腦，n8n 是自動化輸送帶</h2><p>新手最容易卡在這裡。兩個不是互相取代，而是分工合作：一個負責「想」，另一個負責「穩定地把工作送到工具」。</p></div><div class="brainPipe"><article class="roleCard reveal"><div class="roleVisual"><div class="roleHermesArt"><img src="${hermesArt}" alt="Hermes"></div></div><h3>Hermes = 大腦 / AI 員工</h3><p>處理那些需要理解情境、判斷、研究與改變策略的工作。</p><div class="roleBullets"><span>判斷</span><span>思考</span><span>研究</span><span>規劃</span><span>產生內容</span><span>處理例外</span></div></article><div class="roleBridge"><span>Hermes 決定<br>「要做什麼」</span><b class="arrowDown">→</b><span>n8n 負責<br>「把它送去哪」</span></div><article class="roleCard reveal"><div class="roleVisual"><img src="${icons.n8n}" alt="n8n 官方 Logo"></div><h3>n8n = 管線 / 自動化輸送帶</h3><p>把固定流程串起來，讓資料按照規則送去不同服務。</p><div class="roleBullets"><span>Gmail</span><span>Notion</span><span>Google Drive</span><span>資料庫</span><span>Webhook</span><span>其他 SaaS</span></div></article></div></section>
<section class="salesSection" id="demo"><div class="sectionHead reveal"><span class="sectionKicker">3 分鐘 AI AGENT 體驗</span><h2>不要只聽我解釋。選一個工作，看 Hermes 怎麼把任務做下去。</h2><p>這是模擬體驗，不會真的登入你的帳號或發布內容。目的是讓你在三分鐘內理解「Agent 工作流」到底是什麼。</p></div><div class="demoShell reveal"><div class="demoChoices">${Object.entries(demoData).map(([k,v],i)=>`<button class="demoChoice ${i===0?'active':''}" data-demo="${k}">${v.label}</button>`).join('')}</div><div class="demoConsole"><div class="demoPrompt" id="demoPrompt"></div><div class="demoRun" id="demoRun"></div><button class="demoStart" id="demoStart">▶ 讓 Hermes 開始工作</button><div class="demoFinish" id="demoFinish">✅ 這就是你在課程中會親手建立的 AI 工作流程。</div></div></div></section>
<section class="salesSection" id="system-map"><div class="sectionHead sectionCenter reveal"><span class="sectionKicker">完整系統地圖</span><h2>你不是在學一個工具，而是在組一支會協作的 AI 團隊</h2><p>滑鼠移到元件可以看說明；手機點一下即可。先看懂資料怎麼流，再學每一段怎麼做。</p></div><div class="systemMap reveal"><div class="mapStack"><span class="mapNode" data-map="你本人：決定目標、邊界與最後要不要採用結果。">👤 使用者</span><span class="mapArrow">→</span><span class="mapNode" data-map="你可以從手機或電腦把任務交進來。">📲 Telegram / Discord</span><span class="mapArrow">→</span><span class="mapNode core" data-map="AI 員工的大腦：理解任務、研究、決策、使用工具。">⚕ Hermes Agent</span><span class="mapArrow">→</span><span class="mapNode" data-map="把固定動作串成穩定流程，將資料送到不同工具。">🔗 n8n</span></div><div class="mapSub"><span class="mapNode" data-map="理解問題後做選擇，而不是只照固定腳本。">🧠 思考</span><span class="mapNode" data-map="保留工作背景與偏好，讓任務可以延續。">🗂 記憶</span><span class="mapNode" data-map="把常用做法封裝成可重複使用的工作能力。">🧩 Skills</span><span class="mapNode" data-map="搜尋網路、整理多個來源、形成可用資料。">🔎 研究</span><span class="mapNode" data-map="呼叫搜尋、檔案、瀏覽器或其他外部能力。">🛠 工具</span><span class="mapNode" data-map="到了指定時間，自動開始既定工作。">⏰ 自動執行</span></div><div class="mapTools"><span class="toolLogo"><img src="${icons.notion}">Notion</span><span class="toolLogo"><img src="${icons.gmail}">Gmail</span><span class="toolLogo"><img src="${icons.drive}">Google Drive</span><span class="toolLogo"><img src="${icons.telegram}">Telegram</span><span class="toolLogo">🗃 資料庫</span><span class="toolLogo">📣 社群平台</span></div></div><div class="mapTip" id="mapTip"></div></section>
<section class="salesSection" id="outcomes"><div class="sectionHead reveal"><span class="sectionKicker">完成課程後的成果</span><h2>不要只學「Hermes」和「n8n」，要帶走真正能工作的東西</h2><p>每一個成果都可以獨立使用，也可以最後組成你自己的 AI 自媒體工作系統。</p></div><div class="outcomeGrid">${outcomesHtml()}</div></section>
<section class="salesSection" id="course-preview"><div class="sectionHead reveal"><span class="sectionKicker">課程內容預覽</span><h2>前面先讓你看懂價值，真的報名後才一步一步把系統做出來</h2><p>下面保留原本完整的 Top-down 實作內容。不是先背 API 與伺服器，而是先完成第一個可驗收成果，再逐步加上排程、多平台、數據與自我優化。</p></div><div class="coursePreviewBox reveal"><div class="advancedNote"><span>🧭</span><div><b>這一區是進階實作預覽。</b> 完全不懂技術沒關係；你只要先確認前面的概念與 Demo 看得懂。</div></div><div class="grid" id="moduleGrid"></div></div></section>
<section class="salesSection"><div class="sectionHead sectionCenter reveal"><span class="sectionKicker">這堂課適不適合我？</span><h2>不需要人人都學 Agent。適合你，才值得花時間。</h2></div><div class="fitWrap"><div class="fitPanel reveal"><h3>✅ 很適合這些人</h3><div class="fitTags"><span>完全不會寫程式的人</span><span>自媒體創作者</span><span>行銷人</span><span>上班族</span><span>個人品牌</span><span>一人公司</span><span>小型企業</span><span>想學 AI Agent 的人</span></div></div><div class="fitPanel no reveal"><h3>△ 如果你只想要這些，可能不用上</h3><div class="fitTags"><span>只想找一個 AI 聊天機器人</span><span>完全不想自己動手實作</span><span>期待 AI 100% 不需要人工判斷</span><span>只想快速大量洗貼文</span></div></div></div></section>
<section class="salesSection" id="faq"><div class="sectionHead sectionCenter reveal"><span class="sectionKicker">FAQ</span><h2>第一次接觸 AI Agent，你最可能想問的問題</h2><p>這些問題不需要先懂技術才看得懂。</p></div><div class="faqWrap">${faqHtml()}</div></section>
<section class="salesSection"><div class="salesFinal reveal"><h2>不要只是「會用 AI」。<br>開始建立第一位真正能替你工作的 AI 員工。</h2><p>先從一條最小工作流開始：你交代任務 → Hermes 思考 → n8n 串工具 → 結果回到你手上。當第一條跑通，再慢慢擴成自己的 AI 自媒體系統。</p><button class="salesPrimary" id="finalCta">打造我的第一位 AI 員工</button></div><div class="salesFoot">Hermes 自媒體自動化學院｜課前體驗頁 · 正式操作仍以各服務當下官方文件與權限為準</div></section>
<div class="salesModal" id="salesModal"><div class="salesModalCard"><h3>你已經走到課程入口了 🎯</h3><p>這個網站目前是課前體驗版。正式報名網址尚未綁定，因此不會假裝替你完成付款。你可以先看課程實作內容，或再跑一次 3 分鐘體驗。</p><div class="salesModalActions"><button class="salesPrimary" data-modal-scroll="#course-preview">看課程內容</button><button class="salesSecondary" data-modal-scroll="#demo">再玩一次 Demo</button><button class="salesSecondary" id="modalClose">關閉</button></div></div></div>`;
function renderCoursePreview(){const grid=document.getElementById('moduleGrid');if(!grid||typeof modules==='undefined')return;grid.innerHTML=modules.map((m,i)=>{let d=0;try{d=m.cards.filter((_,j)=>state.done.includes(key(i,j))).length}catch(e){}return `<div class="module reveal" data-open-module="${i}"><div class="moduleVisual"><i>${typeof moduleIcon==='function'?moduleIcon(m.title):'✨'}</i><div><span>STEP ${String(i+1).padStart(2,'0')}</span></div></div><h4>${typeof annotateHTML==='function'?annotateHTML(m.title):m.title}</h4><p>${typeof annotateHTML==='function'?annotateHTML(m.desc):m.desc}</p><footer><span>${d}/${m.cards.length} 完成</span><span>預覽 →</span></footer></div>`}).join('')}
renderCoursePreview();
document.body.classList.add('sales-landing');
try{const oldShow=show;show=function(view){document.body.classList.toggle('sales-landing',view==='overview');oldShow(view)}}catch(e){}
document.querySelectorAll('[data-scroll]').forEach(b=>b.addEventListener('click',()=>document.querySelector(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'})));
document.addEventListener('click',e=>{const m=e.target.closest('[data-open-module]');if(m&&typeof openLesson==='function')openLesson(+m.dataset.openModule,0)});
let selected='ig',timer=null;const promptEl=document.getElementById('demoPrompt'),runEl=document.getElementById('demoRun'),finish=document.getElementById('demoFinish'),start=document.getElementById('demoStart');
function paintDemo(){const d=demoData[selected];promptEl.textContent='任務：「'+d.prompt+'」';runEl.innerHTML=d.steps.map((s,i)=>`<div class="demoLine" data-line="${i}"><span class="demoDot"></span><span>${s}</span></div>`).join('');finish.classList.remove('show');start.disabled=false;start.textContent='▶ 讓 Hermes 開始工作'}paintDemo();
document.querySelectorAll('.demoChoice').forEach(b=>b.onclick=()=>{clearInterval(timer);selected=b.dataset.demo;document.querySelectorAll('.demoChoice').forEach(x=>x.classList.toggle('active',x===b));paintDemo()});
start.onclick=()=>{clearInterval(timer);paintDemo();start.disabled=true;start.textContent='Hermes 正在工作…';let i=0;const lines=[...runEl.children];const tick=()=>{if(i>0)lines[i-1]?.classList.add('done');if(i>=lines.length){clearInterval(timer);finish.classList.add('show');start.textContent='↻ 再執行一次';start.disabled=false;return}lines[i].classList.add('on');i++};tick();timer=setInterval(tick,520)};
document.querySelectorAll('.faqQ').forEach(q=>q.onclick=()=>q.parentElement.classList.toggle('open'));
const tip=document.getElementById('mapTip');function openMapTip(el){tip.textContent=el.dataset.map||'';tip.style.display='block';const r=el.getBoundingClientRect();if(innerWidth<=760){tip.style.left='12px';tip.style.right='12px';tip.style.bottom='76px';tip.style.top='auto'}else{tip.style.right='auto';tip.style.bottom='auto';tip.style.left=Math.min(r.left,innerWidth-300)+'px';tip.style.top=(r.bottom+9)+'px'}}function closeMapTip(){tip.style.display='none'}document.querySelectorAll('[data-map]').forEach(el=>{el.addEventListener('mouseenter',()=>openMapTip(el));el.addEventListener('mouseleave',closeMapTip);el.addEventListener('click',e=>{e.stopPropagation();openMapTip(el)})});document.addEventListener('click',closeMapTip);
const io=new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting)x.target.classList.add('in')}),{threshold:.09});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));
const prog=document.getElementById('readingProgress');addEventListener('scroll',()=>{if(!document.body.classList.contains('sales-landing'))return;const h=document.documentElement.scrollHeight-innerHeight;prog.style.width=(h>0?scrollY/h*100:0)+'%'},{passive:true});
const modal=document.getElementById('salesModal');document.getElementById('finalCta').onclick=()=>modal.classList.add('open');document.getElementById('modalClose').onclick=()=>modal.classList.remove('open');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('open')};document.querySelectorAll('[data-modal-scroll]').forEach(b=>b.onclick=()=>{modal.classList.remove('open');document.querySelector(b.dataset.modalScroll)?.scrollIntoView({behavior:'smooth'})});
})();
