(()=>{'use strict';const G=window.HG,{$,T,key,blocked,npc,buildings,dex,questSteps,questTarget,battleTasks}=G;
function tone(freq=520,dur=.07,type='sine',gain=.025){if(!G.save.sound)return;try{G.state.audio=G.state.audio||new (window.AudioContext||window.webkitAudioContext)();const a=G.state.audio,o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.value=freq;g.gain.value=gain;o.connect(g);g.connect(a.destination);o.start();g.gain.exponentialRampToValueAtTime(.0001,a.currentTime+dur);o.stop(a.currentTime+dur)}catch(e){}}
const sfx=t=>t==='ok'?(tone(650,.07),setTimeout(()=>tone(850,.09),70)):t==='bad'?tone(190,.12,'sawtooth',.018):t==='talk'?tone(430,.04,'triangle',.016):t==='step'?tone(160,.025,'square',.006):0;
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1500)}function area(t){const e=$('areaBanner');e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1500)}function panel(html){$('panelContent').innerHTML=html;$('panel').classList.remove('hidden')}function isOverlay(){return !$('dialogue').classList.contains('hidden')||!$('panel').classList.contains('hidden')||!$('battle').classList.contains('hidden')}
function addExp(n){G.save.exp+=n;while(G.save.exp>=100){G.save.exp-=100;G.save.level++;toast(`🌟 升級！Lv.${G.save.level}`);sfx('ok')}G.persist();hud()}function unlock(ids=[]){ids.forEach(id=>{if(!G.save.unlocked.includes(id))G.save.unlocked.push(id)});G.persist()}
function hud(){$('playerLevel').textContent=`Lv. ${G.save.level}`;$('playerTitle').textContent=G.save.level<3?'AI 見習旅人':G.save.level<5?'工作流探險家':'AI 系統 Builder';$('expFill').style.width=G.save.exp+'%';$('expText').textContent=`${G.save.exp} / 100`;$('questList').innerHTML=questSteps.map((q,i)=>`<li class="${i<G.save.quest?'done':''}">${i<G.save.quest?'☑':'☐'} ${q}</li>`).join('');$('explorePct').textContent=Math.min(100,Math.round(Object.keys(G.save.explored||{}).length/8*100))+'%'}
function markExplore(name){G.save.explored=G.save.explored||{};if(!G.save.explored[name]){G.save.explored[name]=1;toast(`🗺️ 發現：${name}`);addExp(8);G.persist()}}
function npcOccupies(x,y,ignore=null){return Object.entries(npc).some(([id,n])=>id!==ignore&&!(id==='boss'&&G.save.bossDown)&&Math.round(n.fx)===x&&Math.round(n.fy)===y)}function canMove(x,y){return x>=2&&y>=2&&x<G.COLS-2&&y<G.ROWS-2&&!blocked.has(key(x,y))&&!npcOccupies(x,y)}
function tryMove(dx,dy,dir){const s=G.state;if(s.moving||isOverlay())return;s.dir=dir;G.save.dir=dir;const nx=G.save.x+dx,ny=G.save.y+dy;if(canMove(nx,ny)){Object.assign(s,{moving:true,fromX:G.save.x,fromY:G.save.y,toX:nx,toY:ny,moveT:0});sfx('step')}else toast('這裡過不去');G.persist()}
function updateNPCs(dt,now){Object.entries(npc).forEach(([id,n])=>{if(id==='boss'||(id===G.state.dialogue&&!$('dialogue').classList.contains('hidden')))return;if(n.moveT<1){n.moveT=Math.min(1,n.moveT+dt/260);n.fx=n.x+(n.tx-n.x)*n.moveT;n.fy=n.y+(n.ty-n.y)*n.moveT;if(n.moveT>=1){n.x=n.tx;n.y=n.ty;n.fx=n.x;n.fy=n.y;n.step++}}else if(now>n.nextMove){n.nextMove=now+1400+Math.random()*2400;const dirs=[[1,0,'right'],[-1,0,'left'],[0,1,'down'],[0,-1,'up'],[0,0,n.dir]],[dx,dy,dir]=dirs[Math.floor(Math.random()*dirs.length)],nx=n.x+dx,ny=n.y+dy,within=Math.abs(nx-n.home[0])<=n.radius&&Math.abs(ny-n.home[1])<=n.radius;if((dx===0&&dy===0)||(within&&!blocked.has(key(nx,ny))&&!(nx===G.save.x&&ny===G.save.y)&&!npcOccupies(nx,ny,id))){n.tx=nx;n.ty=ny;n.moveT=0;n.dir=dir}}})}
function findNear(){let best=null,bd=1.75;Object.entries(npc).forEach(([id,n])=>{if(id==='boss'&&G.save.bossDown)return;const d=Math.hypot(G.save.x-n.fx,G.save.y-n.fy);if(d<bd){best=id;bd=d}});if(Math.hypot(G.save.x-45,G.save.y-15)<2)best='portal';G.state.near=best;const h=$('interactHint');h.classList.toggle('show',!!best);h.querySelector('span').textContent=best==='portal'?'進入課程之門':best==='boss'?'挑戰':'對話'}
function checkArea(){let a='中央廣場';if(G.save.y<10&&G.save.x>13&&G.save.x<25)a='AGENT 研究所';else if(G.save.y<12&&G.save.x>28&&G.save.x<39)a='n8n 自動化工坊';else if(G.save.y>17&&G.save.x<19)a='內容工作室';else if(G.save.y>15&&G.save.x>35)a='數據塔';else if(G.save.x>43)a='課程之門';if(a!==G.state.lastArea){G.state.lastArea=a;area(a);markExplore(a)}}
function checkDoor(){const b=buildings.find(b=>b.door[0]===G.save.x&&b.door[1]===G.save.y);if(!b)return;const i={lab:['🧠','AGENT 研究所','這裡研究 AI Agent 怎麼從「回答問題」進化成「接目標、使用工具、持續完成工作」。'],n8n:['🔗','n8n 自動化工坊','這裡把 Notion、Gmail、Drive、Webhook 與其他工具串成穩定的自動化管線。'],studio:['✍️','內容工作室','這裡把研究、選題、腳本、文案與素材整理成一條內容生產線。'],tower:['📊','數據塔','這裡把觸及、分享、收藏、點擊等成效送回 Agent，讓下一輪策略更好。']}[b.id];panel(`<div class="interior-scene"><div class="interior-icon">${i[0]}</div><h2>${i[1]}</h2><p>${i[2]}</p><div class="interior-floor"><span>📚</span><span>🖥️</span><span>🧩</span><span>💡</span></div><button class="primary-btn" id="leaveInterior">走出建築</button></div>`);setTimeout(()=>{$('leaveInterior').onclick=()=>$('panel').classList.add('hidden')},0);markExplore(b.name)}
function drawPortrait(id){const host=$('speakerAvatar');host.innerHTML='<canvas width="128" height="128"></canvas>';const c=host.firstChild,p=c.getContext('2d'),s=npc[id]?.style||{},skin='#efc3a4',hair=s.hair||'#24372e',body=s.outfit||'#476dff';p.imageSmoothingEnabled=false;p.fillStyle='#10243d';p.fillRect(0,0,128,128);p.fillStyle=body;p.fillRect(32,84,64,44);p.fillStyle=skin;p.fillRect(39,39,50,45);p.fillStyle=hair;p.fillRect(35,26,58,22);if(s.robot){p.fillStyle='#c7efff';p.fillRect(39,44,50,31);p.fillStyle='#2c69bd';p.fillRect(49,60,8,8);p.fillRect(71,60,8,8)}else{p.fillStyle='#132a31';p.fillRect(50,60,7,7);p.fillRect(71,60,7,7);p.fillStyle='#95554e';p.fillRect(60,78,9,4)}if(s.glasses){p.strokeStyle='#1d3444';p.lineWidth=4;p.strokeRect(43,54,18,15);p.strokeRect(67,54,18,15);p.fillRect(61,59,6,3)}if(s.goggles){p.fillStyle='#172430';p.fillRect(38,30,52,10);p.fillStyle='#ffb349';p.fillRect(46,31,14,8);p.fillRect(69,31,14,8)}}
function openDialogue(id){G.state.dialogue=id;G.state.dialoguePage=0;renderDialogue();$('dialogue').classList.remove('hidden');sfx('talk')}function renderDialogue(){const n=npc[G.state.dialogue],p=n.dialog[G.state.dialoguePage];$('speakerName').textContent=n.name;drawPortrait(G.state.dialogue);$('dialogueText').innerHTML=`${p[0]}<small>${p[1]}</small>`;$('dialogueMood').textContent=`表情：${({teach:'講解中',point:'指引方向',calm:'冷靜分析',happy:'理解了！',confident:'自信',worried:'快被工作淹沒',alert:'發現問題',angry:'生氣'})[p[2]]||'對話中'}`}
function completeDialogue(id){unlock(npc[id].unlock);addExp(25);if(id===questTarget[G.save.quest]){G.save.quest=Math.min(7,G.save.quest+1);toast('✅ 主線更新');sfx('ok')}G.persist();hud()}function nextDialogue(){const n=npc[G.state.dialogue];if(G.state.dialoguePage<n.dialog.length-1){G.state.dialoguePage++;renderDialogue();sfx('talk');return}const id=G.state.dialogue;$('dialogue').classList.add('hidden');G.state.dialogue=null;completeDialogue(id);if(id==='creator')toast('新任務：挑戰「重複工作怪」')}
function openBattle(){if(G.save.quest<5){openDialogue('boss');return}$('battle').classList.remove('hidden');renderBattle()}function renderBattle(){const i=G.save.battle||0;$('monsterHp').style.width=(100-i/battleTasks.length*100)+'%';if(i>=battleTasks.length){$('battleQuestion').textContent='混亂值歸零！你已經分清 Hermes 和 n8n 的工作。';document.querySelector('.battle-actions').style.display='none';$('battleFeedback').textContent='🏅 獲得：工作流修復師';if(!G.save.ach.includes('workflow'))G.save.ach.push('workflow');G.save.bossDown=true;if(G.save.quest===5)G.save.quest=6;unlock(['workflow']);G.persist();hud();sfx('ok');return}document.querySelector('.battle-actions').style.display='grid';$('battleQuestion').textContent=battleTasks[i][0];$('battleFeedback').textContent=''}function answerBattle(ans){const i=G.save.battle||0,c=battleTasks[i]?.[1];if(!c)return;if(ans===c){$('battleFeedback').textContent=c==='hermes'?'答對！這件事需要理解與判斷。':'答對！這是固定串接與資料搬運。';G.save.battle=i+1;addExp(12);G.persist();sfx('ok');setTimeout(renderBattle,500)}else{$('battleFeedback').textContent='再想一下：它比較像「需要思考」還是「固定執行」？';sfx('bad')}}
function openGate(){if(G.save.quest<7){panel(`<h2>🚪 課程之門還沒完全開啟</h2><p>你目前走到主線第 ${G.save.quest+1} 站。先把 Agent、Hermes、n8n、工作流與數據回饋走完。</p>`);return}G.save.quest=8;G.persist();hud();panel(`<h2>🎓 你已經通過 AI 自媒體城</h2><p>人決定目標 → Hermes 負責思考／研究／內容 → n8n 負責串接／搬運 → 工具執行 → 數據再回來。</p><button class="primary-btn" id="courseCta">打造我的第一位 AI 員工</button>`);setTimeout(()=>{$('courseCta').onclick=()=>alert('目前是課前體驗版；正式報名連結尚未綁定。')},0)}
function interact(){if(!G.state.near)return;if(G.state.near==='portal')openGate();else if(G.state.near==='boss')openBattle();else openDialogue(G.state.near)}
function openPanel(type){if(type==='dex')panel(`<h2>📕 Agent 圖鑑</h2><div class="dex-grid">${dex.map(d=>`<article class="info-card ${G.save.unlocked.includes(d[0])?'':'locked'}"><div class="icon">${G.save.unlocked.includes(d[0])?d[3]:'❓'}</div><h3>${G.save.unlocked.includes(d[0])?d[1]:'尚未發現'}</h3><p>${G.save.unlocked.includes(d[0])?d[2]:'繼續探索並和 NPC 對話。'}</p></article>`).join('')}</div>`);else if(type==='bag')panel(`<h2>🎒 背包</h2><div class="bag-grid">${G.save.inventory.map(x=>`<article class="info-card"><div class="icon">📦</div><h3>${x}</h3><p>冒險過程中取得的學習道具。</p></article>`).join('')}</div>`);else if(type==='achieve')panel(`<h2>🏆 成就</h2><div class="ach-grid"><article class="info-card ${G.save.ach.includes('workflow')?'':'locked'}"><div class="icon">🏅</div><h3>工作流修復師</h3><p>打倒重複工作怪。</p></article></div>`);else{panel(`<h2>⚙️ 設定</h2><p>V11 使用正常模組腳本，不再使用 eval。</p><label><input id="soundToggle" type="checkbox" ${G.save.sound?'checked':''}> 開啟音效</label><br><button id="resetProgress" class="soft-btn" style="margin-top:18px">清除進度重新開始</button>`);setTimeout(()=>{$('soundToggle').onchange=e=>{G.save.sound=e.target.checked;G.persist()};$('resetProgress').onclick=()=>{try{localStorage.removeItem('hermes_rpg_v11')}catch(e){}location.reload()}},0)}}
function tick(dt,now){const s=G.state;if(s.moving){s.moveT+=dt/150;if(s.moveT>=1){s.moveT=1;G.save.x=s.toX;G.save.y=s.toY;s.moving=false;G.persist();checkArea();checkDoor();findNear()}}updateNPCs(dt,now);if(!s.moving)findNear()}
function controls(){addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d'].includes(k))e.preventDefault();if(['arrowup','w'].includes(k))tryMove(0,-1,'up');if(['arrowdown','s'].includes(k))tryMove(0,1,'down');if(['arrowleft','a'].includes(k))tryMove(-1,0,'left');if(['arrowright','d'].includes(k))tryMove(1,0,'right');if(k==='e'&&!isOverlay())interact();if(e.key==='Escape'){$('dialogue').classList.add('hidden');$('panel').classList.add('hidden');$('battle').classList.add('hidden')}});document.querySelectorAll('[data-dir]').forEach(b=>{let timer=null;const go=()=>{const d=b.dataset.dir;if(d==='up')tryMove(0,-1,'up');if(d==='down')tryMove(0,1,'down');if(d==='left')tryMove(-1,0,'left');if(d==='right')tryMove(1,0,'right')};b.addEventListener('pointerdown',e=>{e.preventDefault();go();timer=setInterval(go,190)});['pointerup','pointercancel','pointerleave'].forEach(ev=>b.addEventListener(ev,()=>{clearInterval(timer);timer=null}))});$('mobileAction').onclick=interact}
function start(fresh=false){if(fresh){G.save=G.freshSave();G.persist()}G.state.started=true;G.state.dir=G.save.dir||'down';$('splash').classList.add('hidden');$('bootStatus').classList.add('hidden');area('AI 自媒體城');hud();findNear();markExplore('中央廣場');sfx('ok')}
Object.assign(G,{hud,tick,controls,start,nextDialogue,openPanel,answerBattle,interact});
})();