plugins {
    id 'com.android.application'
}

android {
    namespace 'tw.com.tft.documentscanner'
    compileSdk 35

    defaultConfig {
        applicationId 'tw.com.tft.documentscanner'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
        ndk { abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86_64' }
    }

    buildTypes {
        debug { minifyEnabled false }
        release {
            signingConfig signingConfigs.debug
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        jniLibs { useLegacyPackaging true }
        resources { excludes += ['/META-INF/{AL2.0,LGPL2.1}'] }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.activity:activity:1.10.1'
    implementation 'androidx.core:core:1.16.0'
    implementation 'androidx.exifinterface:exifinterface:1.4.1'
    implementation 'com.google.android.material:material:1.12.0'
    implementation 'com.google.android.gms:play-services-mlkit-document-scanner:16.0.0'
    implementation 'org.opencv:opencv:4.14.0'
}
