plugins {
    id 'com.android.application'
}

android {
    namespace 'com.tft.purchase'
    compileSdk 35

    defaultConfig {
        applicationId 'com.tft.purchase'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0.0'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'com.google.mlkit:text-recognition-chinese:16.0.1'
}
