(()=>{'use strict';
const $=id=>document.getElementById(id);
const screens=['introScreen','mapScreen','gameScreen','clearScreen'];
const AMMO={hermes:{label:'Hermes',icon:'🧠',sub:'思考 / 判斷',color:'#657ffc'},n8n:{label:'n8n',icon:'🔗',sub:'串接 / 執行',color:'#49b896'},chatgpt:{label:'ChatGPT',icon:'💬',sub:'問答 / 產出',color:'#ef9a50'},cron:{label:'Cron',icon:'⏰',sub:'固定時間啟動',color:'#a980ef'},human:{label:'你本人',icon:'🧑‍💼',sub:'最後決策',color:'#ef6572'}};
const levels=[
 {title:'Agent 新手村',icon:'🤖',desc:'先搞懂：ChatGPT 與 Agent 到底差在哪。',lesson:'ChatGPT 像聰明顧問；Hermes Agent 更像會持續把工作做下去的 AI 員工。',task:'比較 10 則 AI 新聞，挑出今天最值得做的一題。',correct:'hermes',enemy:'👾',hp:2,wind:0,ammo:['hermes','chatgpt'],badge:'Agent 新兵',summary:[['💬','ChatGPT','回答與產出'],['🧠','Hermes','判斷並繼續做事'],['🎯','關鍵','是否會把任務往下完成']]},
 {title:'大腦與輸送帶',icon:'🔗',desc:'搞懂 Hermes 與 n8n 的工作分工。',lesson:'Hermes 負責「想要做什麼」；n8n 負責「把東西穩定送到哪裡」。',task:'把已完成的 IG 文案自動存進 Notion，再傳 Telegram 通知。',correct:'n8n',enemy:'🧌',hp:2,wind:1,ammo:['hermes','n8n'],badge:'流程學徒',summary:[['🧠','Hermes','大腦：思考與判斷'],['🔗','n8n','管線：串接與執行'],['🤝','合作','Hermes 決定，n8n 執行']]},
 {title:'工作流峽谷',icon:'🧩',desc:'把 AI 工作拆成可以自動往下跑的流程。',lesson:'工作流不是一個超大的 AI，而是一連串角色各自做擅長的事。',task:'先研究主題，再寫文案；完成後交給工具存檔。這一砲應由誰先出手？',correct:'hermes',enemy:'🪨',hp:3,wind:-1,ammo:['hermes','n8n','chatgpt'],badge:'工作流組裝師',summary:[['🔎','研究','先理解問題'],['✍️','產出','形成可用內容'],['📦','交接','再交給自動化管線']]},
 {title:'排程風谷',icon:'⏰',desc:'讓系統不是等你想到才做，而是自己準時開始。',lesson:'Cron 就像 AI 員工的鬧鐘：時間到，自動把任務叫醒。',task:'每天早上 09:00 自動開始蒐集 AI 新聞。需要哪個能力來「準時叫醒任務」？',correct:'cron',enemy:'🌪️',hp:2,wind:2,ammo:['cron','hermes','n8n'],badge:'排程導航員',summary:[['⏰','Cron','決定什麼時候開始'],['🧠','Hermes','醒來後決定怎麼做'],['🔗','n8n','把結果送往下一站']]},
 {title:'自媒體工廠',icon:'📣',desc:'把研究、產出、存檔、通知串成一條線。',lesson:'真正省時間的不是「AI 寫一篇文」，而是整條流程不用你一直搬資料。',task:'把 Hermes 已經完成的 YouTube 腳本存進 Google Drive。',correct:'n8n',enemy:'🏭',hp:3,wind:-2,ammo:['n8n','hermes','chatgpt'],badge:'自媒體工程師',summary:[['🧠','研究 / 寫稿','交給 Agent'],['🔗','存檔 / 通知','交給 n8n'],['📣','成果','你只看結果與例外']]},
 {title:'重複工作魔王',icon:'👹',desc:'最後一關：判斷什麼該自動、什麼一定要人決定。',lesson:'好的 Agent 系統不是什麼都自動。高風險、品牌判斷與最後責任，仍然要有人。',task:'一篇涉及公司危機回應的貼文，最後「是否發布」應該交給誰決定？',correct:'human',enemy:'👹',hp:4,wind:3,ammo:['hermes','n8n','human'],badge:'AI 系統指揮官',boss:true,summary:[['🤖','AI','做大量研究與準備'],['🧑‍💼','人','高風險最後決定'],['🏆','成熟系統','自動化 ≠ 放棄控制']]}
];
const state={unlocked:1,stars:0,xp:0,completed:{},level:0,ammo:null,shots:0,hits:0,enemyHp:2,sound:true,firing:false,trajectory:null};
try{Object.assign(state,JSON.parse(localStorage.getItem('agent_cannon_v1')||'{}'))}catch(e){}
function save(){try{localStorage.setItem('agent_cannon_v1',JSON.stringify({unlocked:state.unlocked,stars:state.stars,xp:state.xp,completed:state.completed}))}catch(e){}}
function show(id){screens.forEach(s=>$(s).classList.toggle('active',s===id));window.scrollTo({top:0,behavior:'smooth'})}
function sound(freq=440,dur=.08,type='sine'){if(!state.sound)return;try{const ac=sound.ac||(sound.ac=new (AudioContext||webkitAudioContext)()),o=ac.createOscillator(),g=ac.createGain();o.type=type;o.frequency.value=freq;g.gain.value=.05;o.connect(g);g.connect(ac.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,ac.currentTime+dur);o.stop(ac.currentTime+dur)}catch(e){}}
$('howBtn').onclick=()=>$('introHow').classList.remove('hidden');$('howClose').onclick=()=>$('introHow').classList.add('hidden');
$('startGameBtn').onclick=()=>{show('mapScreen');renderMap()};
$('resetBtn').onclick=()=>{if(confirm('要清除闖關進度重新開始嗎？')){state.unlocked=1;state.stars=0;state.xp=0;state.completed={};save();renderMap()}};
function renderMap(){ $('mapXp').textContent=`Lv.${1+Math.floor(state.xp/120)} · ${state.xp} XP`; $('mapStars').textContent=`⭐ ${state.stars}`; $('levelMap').innerHTML=levels.map((l,i)=>{const done=state.completed[i],locked=i>=state.unlocked;return `<article class="level-card ${locked?'locked':''} ${done?'done':''} ${l.boss?'boss-card':''}"><div class="cloud"></div><div class="level-icon">${l.icon}</div><span class="eyebrow">STAGE ${i+1}</span><h3>${l.title}</h3><p>${l.desc}</p><div class="level-meta"><span>${locked?'🔒 前一關完成後解鎖':done?'已通關':'可挑戰'}</span><button type="button" data-level="${i}" ${locked?'disabled':''}>${done?'再玩一次':'進入關卡'}</button></div><div class="level-stars">${done?'⭐'.repeat(done.stars):''}</div></article>`}).join('');$('levelMap').querySelectorAll('button[data-level]').forEach(b=>b.onclick=()=>startLevel(+b.dataset.level))}
$('backMapBtn').onclick=()=>{show('mapScreen');renderMap()};
$('clearMapBtn').onclick=()=>{show('mapScreen');renderMap()};
$('nextStageBtn').onclick=()=>{const n=state.level+1;if(n<levels.length)startLevel(n);else{show('mapScreen');renderMap()}};
$('lessonDismiss').onclick=()=>$('lessonStrip').style.display='none';$('soundBtn').onclick=()=>{state.sound=!state.sound;$('soundBtn').textContent=state.sound?'🔊':'🔇'};
const canvas=$('gameCanvas'),ctx=canvas.getContext('2d');let anim=0,particles=[];
function startLevel(i){state.level=i;const l=levels[i];state.enemyHp=l.hp;state.shots=0;state.hits=0;state.ammo=l.ammo[0];state.firing=false;state.trajectory=null;$('lessonStrip').style.display='grid';$('stageNo').textContent=`STAGE ${i+1}`;$('stageTitle').textContent=l.title;$('hudStars').textContent=state.stars;$('hudXp').textContent=state.xp;$('lessonText').textContent=l.lesson;$('enemyEmoji').textContent=l.enemy;$('enemyTask').textContent=l.task;$('windText').textContent=(l.wind>0?'→ ':l.wind<0?'← ':'→ ')+Math.abs(l.wind);const defaults=[[45,54],[45,53],[45,55],[45,51],[45,56],[45,50]][i];$('angleRange').value=defaults[0];$('powerRange').value=defaults[1];updateSliders();renderAmmo();updateHp();$('resultPop').classList.add('hidden');show('gameScreen');cancelAnimationFrame(anim);loop()}
function renderAmmo(){const l=levels[state.level];$('ammoRow').innerHTML=l.ammo.map(k=>`<button type="button" class="ammo-btn ${state.ammo===k?'active':''}" data-ammo="${k}"><span>${AMMO[k].icon}</span><b>${AMMO[k].label}<small>${AMMO[k].sub}</small></b></button>`).join('');$('ammoRow').querySelectorAll('[data-ammo]').forEach(b=>b.onclick=()=>{state.ammo=b.dataset.ammo;renderAmmo();sound(540,.06)})}
function updateSliders(){$('angleOut').textContent=$('angleRange').value+'°';$('powerOut').textContent=$('powerRange').value+'%'}$('angleRange').oninput=updateSliders;$('powerRange').oninput=updateSliders;
$('assistBtn').onclick=()=>{const ang=[45,45,45,45,45,45][state.level],pow=[54,53,55,51,56,50][state.level];$('angleRange').value=ang;$('powerRange').value=pow;updateSliders();$('assistText').textContent=`建議：角度約 ${ang}°、力度約 ${pow}%（風會影響）`;sound(660,.08)};
function updateHp(){const l=levels[state.level];$('enemyHpFill').style.width=Math.max(0,state.enemyHp/l.hp*100)+'%'}
function terrainY(x){return 535+45*Math.sin(x/150)+18*Math.sin(x/58)}
function drawWorld(t){const w=canvas.width,h=canvas.height;const grad=ctx.createLinearGradient(0,0,0,h);grad.addColorStop(0,'#91d6f7');grad.addColorStop(.55,'#d8f3ff');grad.addColorStop(1,'#f8edcb');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);ctx.fillStyle='rgba(255,255,255,.82)';for(let i=0;i<6;i++){const x=(i*230+(t*.012*(i%2?1:-1)))%(w+260)-130,y=70+(i%3)*62;cloud(x,y,1+(i%2)*.3)}island(170,260,150,'#77c694');island(930,220,170,'#68bcb2');ctx.beginPath();ctx.moveTo(0,h);for(let x=0;x<=w;x+=8)ctx.lineTo(x,terrainY(x));ctx.lineTo(w,h);ctx.closePath();ctx.fillStyle='#7fbe68';ctx.fill();ctx.strokeStyle='#5b9f55';ctx.lineWidth=5;ctx.stroke();ctx.beginPath();ctx.moveTo(0,h);for(let x=0;x<=w;x+=8)ctx.lineTo(x,terrainY(x)+26);ctx.lineTo(w,h);ctx.closePath();ctx.fillStyle='#af8454';ctx.fill();for(let x=50;x<1150;x+=80){const y=terrainY(x)-5;ctx.fillStyle='#4f9450';ctx.fillRect(x,y-18,4,18);ctx.beginPath();ctx.arc(x-5,y-17,6,0,Math.PI*2);ctx.arc(x+6,y-21,7,0,Math.PI*2);ctx.fill()}const py=terrainY(125)-58;ctx.save();ctx.translate(125,py);ctx.fillStyle='rgba(30,51,66,.18)';ellipse(0,58,40,12);ctx.font='52px sans-serif';ctx.textAlign='center';ctx.fillText('🧑‍🚀',0,38);ctx.restore();drawCannon(185,terrainY(185)-34,+$('angleRange').value);const ex=1015,ey=terrainY(1015)-65;ctx.save();ctx.translate(ex,ey);const bounce=Math.sin(t/240)*5;ctx.translate(0,bounce);ctx.fillStyle='rgba(44,35,58,.18)';ellipse(0,65,48,12);ctx.font=(levels[state.level].boss?'76':'64')+'px sans-serif';ctx.textAlign='center';ctx.fillText(levels[state.level].enemy,0,42);ctx.restore();if(!state.firing)drawPreview();if(state.trajectory)drawProjectile();particles.forEach(p=>{ctx.globalAlpha=Math.max(0,p.life);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1});particles=particles.filter(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.18;p.life-=.025;return p.life>0})}
function cloud(x,y,s){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.beginPath();ctx.arc(0,0,27,0,Math.PI*2);ctx.arc(30,-8,34,0,Math.PI*2);ctx.arc(65,2,25,0,Math.PI*2);ctx.fill();ctx.restore()}
function island(x,y,r,c){ctx.save();ctx.translate(x,y);ctx.fillStyle=c;ctx.beginPath();ctx.ellipse(0,0,r,r*.42,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#97714f';ctx.beginPath();ctx.moveTo(-r*.72,8);ctx.quadraticCurveTo(0,r*.95,r*.72,8);ctx.quadraticCurveTo(0,r*.45,-r*.72,8);ctx.fill();ctx.restore()}
function ellipse(x,y,rx,ry){ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill()}
function drawCannon(x,y,ang){ctx.save();ctx.translate(x,y);ctx.fillStyle='#405a70';ctx.beginPath();ctx.arc(0,5,24,0,Math.PI*2);ctx.fill();ctx.rotate(-ang*Math.PI/180);ctx.fillStyle='#31485c';ctx.fillRect(0,-8,58,16);ctx.fillStyle='#577189';ctx.fillRect(42,-11,22,22);ctx.restore()}
function physics(){const ang=+$('angleRange').value*Math.PI/180,p=+$('powerRange').value;const speed=6.9+p*.105;return {x:225,y:terrainY(185)-45,vx:Math.cos(ang)*speed,vy:-Math.sin(ang)*speed,wind:levels[state.level].wind*.0045}}
function drawPreview(){let p=physics(),x=p.x,y=p.y,vx=p.vx,vy=p.vy;ctx.fillStyle='rgba(255,255,255,.8)';for(let i=0;i<55;i++){vx+=p.wind;vy+=.19;x+=vx;y+=vy;if(i%5===0){ctx.beginPath();ctx.arc(x,y,3.5,0,Math.PI*2);ctx.fill()}if(y>terrainY(x)||x>canvas.width)break}}
function drawProjectile(){const p=state.trajectory;ctx.fillStyle=AMMO[p.ammo].color;ctx.beginPath();ctx.arc(p.x,p.y,10,0,Math.PI*2);ctx.fill();ctx.font='17px sans-serif';ctx.textAlign='center';ctx.fillText(AMMO[p.ammo].icon,p.x,p.y+6)}
function loop(t=0){drawWorld(t);if(state.trajectory)stepProjectile();anim=requestAnimationFrame(loop)}
function stepProjectile(){const p=state.trajectory;p.vx+=p.wind;p.vy+=.19;p.x+=p.vx;p.y+=p.vy;const ex=1015,ey=terrainY(1015)-35,hit=Math.hypot(p.x-ex,p.y-ey)<54;if(hit){impact(true);return}if(p.y>terrainY(Math.max(0,Math.min(canvas.width,p.x)))||p.x>canvas.width+20||p.y>canvas.height+30){impact(false)}}
function impact(hit){const p=state.trajectory;state.trajectory=null;state.firing=false;$('fireBtn').disabled=false;state.shots++;for(let i=0;i<28;i++)particles.push({x:p.x,y:p.y,vx:(Math.random()-.5)*8,vy:(Math.random()-.7)*7,r:2+Math.random()*5,life:1,color:i%2?AMMO[p.ammo].color:'#fff4a8'});if(!hit){popup('差一點！','先調角度或力度，再試一次。');sound(190,.14,'sawtooth');return}state.hits++;if(p.ammo===levels[state.level].correct){state.enemyHp--;updateHp();popup('💥 概念命中！',correctExplain(state.level));sound(720,.12,'square');setTimeout(()=>sound(920,.11,'square'),80);if(state.enemyHp<=0)setTimeout(clearLevel,900)}else{popup('命中了，但能力選錯了',wrongExplain(p.ammo,state.level));sound(210,.14,'triangle')}}
function popup(title,text){$('resultTitle').textContent=title;$('resultText').textContent=text;$('resultPop').classList.remove('hidden');setTimeout(()=>$('resultPop').classList.add('hidden'),2200)}
function correctExplain(i){return ['這件事需要比較、判斷與選題，所以交給 Hermes。','這件事是固定的存檔＋通知流程，所以交給 n8n。','研究與判斷應先由 Hermes 出手。','Cron 負責在指定時間叫醒任務。','固定把完成稿送進 Drive，交給 n8n 最穩。','危機回應要承擔責任，最後發布應由人決定。'][i]}
function wrongExplain(ammo,i){if(ammo==='n8n')return 'n8n 很會照規則執行，但不適合負責複雜判斷。';if(ammo==='hermes')return 'Hermes 很會思考，但固定搬運與串接通常交給 n8n 更穩。';if(ammo==='chatgpt')return 'ChatGPT 可以回答與產出，但這一題需要的是持續執行 / 判斷能力。';if(ammo==='cron')return 'Cron 只負責「什麼時候開始」，不負責內容判斷。';return '高風險最後責任不應完全交給自動化。'}
$('fireBtn').onclick=fire;addEventListener('keydown',e=>{if(e.code==='Space'&&$('gameScreen').classList.contains('active')&&!['INPUT','BUTTON'].includes(document.activeElement.tagName)){e.preventDefault();fire()}});
function fire(){if(state.firing)return;state.firing=true;$('fireBtn').disabled=true;const p=physics();state.trajectory={...p,ammo:state.ammo};sound(330,.09,'square');setTimeout(()=>sound(210,.1,'square'),55)}
function clearLevel(){const l=levels[state.level];const ratio=Math.max(1,3-Math.floor((state.shots-l.hp)/2)),stars=Math.min(3,ratio);const prev=state.completed[state.level]?.stars||0;if(stars>prev)state.stars+=stars-prev;state.completed[state.level]={stars};state.unlocked=Math.max(state.unlocked,state.level+2);const gain=35+stars*10;state.xp+=gain;save();$('clearStars').textContent='⭐'.repeat(stars)+'☆'.repeat(3-stars);$('rewardBadge').textContent=l.badge;$('rewardXp').textContent=gain+' XP';$('learningSummary').innerHTML=l.summary.map(s=>`<div class="summary-cell"><span>${s[0]}</span><b>${s[1]}</b><small>${s[2]}</small></div>`).join('');$('nextStageBtn').textContent=state.level===levels.length-1?'完成冒險 →':'下一關 →';show('clearScreen');sound(740,.15,'square');setTimeout(()=>sound(940,.15,'square'),100)}
renderMap();
})();
